### ISSUE TITLE
不能平滑重启

### ISSUE THREAD

**Issue by buexplain** [fevin/gracehttp#2]
## main.go代码
```golang
package main

import (
	"github.com/fevin/gracehttp"
	"net/http"
	"os"
	"strconv"
	"time"
)

func main() {
	mux := http.NewServeMux()

	mux.HandleFunc("/slow", func(writer http.ResponseWriter, request *http.Request) {
		_ = request.ParseForm()
		t, _ := strconv.Atoi(request.Form.Get("ms"))
		if t > 0 {
			<- time.After(time.Duration(t)*time.Millisecond)
		}
		writer.WriteHeader(http.StatusOK)
		_, _ = writer.Write([]byte(strconv.Itoa(os.Getpid())))
	})

	server := &http.Server{
		Addr:":1991",
		Handler: mux,
	}

	gracehttp.AddServer(server, false, "", "")
	gracehttp.Run()
}
```
## 编译运行
```bash
go build main.go && ./main
```
## 测试
```bash
kill -HUP 4594
```
## 报错
```bash
2019/06/10 15:59:01 [gracehtto-log][Info] [Received SIG. [PID:4594, SIG:hangup]] 
2019/06/10 15:59:01 [gracehtto-log][Info] [start new process success, pid 4610.] 
[root@dev-php testgo-x]# panic: Get listener fail. err:%!(EXTRA *errors.errorString=net.Listen error: listen tcp :1991: bind: address already in use) [recovered]
	panic: Get listener fail. err:%!(EXTRA *errors.errorString=net.Listen error: listen tcp :1991: bind: address already in use)

goroutine 1 [running]:
github.com/fevin/gracehttp.Run.func1()
	/root/go/pkg/mod/github.com/fevin/gracehttp@v0.0.0-20180704031102-206ea8c761fa/gracehttp.go:50 +0x62
panic(0x694860, 0xc00012e030)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/fevin/gracehttp.(*Server).ListenAndServe(0xc000128000)
	/root/go/pkg/mod/github.com/fevin/gracehttp@v0.0.0-20180704031102-206ea8c761fa/server.go:59 +0x20d
github.com/fevin/gracehttp.(*Server).Run(0xc000128000)
	/root/go/pkg/mod/github.com/fevin/gracehttp@v0.0.0-20180704031102-206ea8c761fa/server.go:47 +0x44
github.com/fevin/gracehttp.Run()
	/root/go/pkg/mod/github.com/fevin/gracehttp@v0.0.0-20180704031102-206ea8c761fa/gracehttp.go:57 +0x6b
main.main()
	/opt/www/testgo-x/main.go:30 +0xe0
```

**Comment by fevin** [comment]
`gracehttp` 平滑重启时，依赖 flag 参数，所以需要先调用
`flag.Parse()`
不然会导致重启时，子进程不能识别是否是重启。

我已经做了一些优化，在调用 `gracehttp.Run` 方式里，判断如果 `flag` 没有解析，会主动调用一次 `flag.Parse()`

commit:[增加 flag 缺省解析功能](https://github.com/fevin/gracehttp/commit/df342f692bb137540af35d26488b6470142a5fdc)
